version: "3.8"
networks:
  backend:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goserver_api
    ports:
      - "9191:9090"
    volumes:
      - ./:/app
    networks:
       - backend
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-server
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=supersecretpassword
    ports:
          - '5432:5432'
    volumes:
          - db:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  db:
    driver: local